# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import truckpad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('object_id', models.UUIDField(default=truckpad.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('cpf_no', models.CharField(max_length=30, unique=True, verbose_name='CPF Number')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('gender', models.IntegerField(choices=[(0, 'Secret'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='Gender')),
                ('drive_license_type', models.CharField(max_length=10, null=True, verbose_name='CNH Type')),
                ('has_truck', models.BooleanField(default=False, verbose_name='Has Truck')),
            ],
            options={
                'verbose_name': 'Truck Driver',
                'verbose_name_plural': 'Truck Drivers',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('object_id', models.UUIDField(default=truckpad.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('is_loaded', models.BooleanField(default=True, verbose_name='Is Truck Enter loaded?')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='truckpad.Driver', verbose_name='Driver')),
            ],
            options={
                'verbose_name': 'Entrance Registration',
                'verbose_name_plural': 'Entrance Registrations',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('object_id', models.UUIDField(default=truckpad.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('object_id', models.UUIDField(default=truckpad.models.gen_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Truck number')),
                ('truck_type', models.IntegerField(choices=[(1, 'Caminhão 3/4'), (2, 'Caminhão Toco'), (3, 'Caminhão Truck'), (4, 'Caminhão Simples'), (5, 'Caminhão Eixo Extendido')], verbose_name='Truck type')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='from_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_registrations', to='truckpad.Terminal', verbose_name='From Terminal'),
        ),
        migrations.AddField(
            model_name='registration',
            name='to_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_registrations', to='truckpad.Terminal', verbose_name='To Terminal'),
        ),
        migrations.AddField(
            model_name='registration',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='truckpad.Truck', verbose_name='Truck'),
        ),
        migrations.AddField(
            model_name='driver',
            name='from_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_drivers', to='truckpad.Terminal', verbose_name='Source Terminal'),
        ),
        migrations.AddField(
            model_name='driver',
            name='to_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enter_drivers', to='truckpad.Terminal', verbose_name='Destination Terminal'),
        ),
    ]
